<?php
/**
 * Copyright (C) EC Brands Corporation - All Rights Reserved
 * Contact Licensing@ECInternet.com for use guidelines
 */
declare(strict_types=1);
?>

<?php /** @var \ECInternet\Paytelligence\Block\Card\NewAction $block */ ?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>

<div id="paytelligence-card-form">
    <form class="form contact"
          action="<?= $block->getUrl('paytelligence/card/save', ['_secure' => true]) ?>"
          id="card-form"
          method="post"
          data-hasrequired="<?= __('* Required Fields') ?>"
          data-mage-init='{"validation": {}}'>
        <fieldset class="fieldset">
            <legend class="legend">
                <span><?= $escaper->escapeHtml(__('Card Details')) ?></span>
            </legend>
            <br />

            <!-- Credit Card Number - cc_number -->
            <div class="field cardnumber required">
                <label class="label" for="cardnumber">
                    <span><?= __('Card Number') ?></span>
                </label>
                <div class="control">
                    <input name="cardnumber"
                           id="cardnumber"
                           title="<?= __('Card Number') ?>"
                           class="input-text"
                           type="number"
                           data-validate="{'required-number':true}"
                    />
                </div>
            </div>

            <!-- Expiration Date - cc_exp_month, cc_exp_year -->
            <div class="field expmonth required">
                <label class="label" for="expmonth">
                    <span><?= __('Expiration Month') ?></span>
                </label>
                <div class="control">
                    <select name="expmonth"
                            id="expmonth"
                            title="<?= __('Expiration Month') ?>"
                            class="select select-month"
                            data-validate="{'required':true,'validate-cc-exp': '#expyear'}"
                    >
                        <?php foreach ($block->getCcMonths() as $key => $value) { ?>
                            <option value="<?= $escaper->escapeHtml($key) ?>">
                                <?= $escaper->escapeHtml($value) ?>
                            </option>
                        <?php } ?>
                    </select>
                </div>
            </div>

            <div class="field expyear required">
                <label class="label" for="expyear">
                    <span><?= __('Expiration Year') ?></span>
                </label>
                <div class="control">
                    <select name="expyear"
                            id="expyear"
                            title="<?= __('Expiration Year') ?>"
                            class="select select-year"
                            data-validate="{'required':true}"
                    >
                        <?php foreach ($block->getCcYears() as $key => $value): ?>
                            <option value="<?= /* @noEscape */ $key ? $escaper->escapeHtml($key) : '' ?>">
                                <?= $escaper->escapeHtml($value) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>

            <!-- Card Verification Number - cc_cid -->
            <div class="field cvv required">
                <label class="label" for="cvv">
                    <span><?= __('CVV') ?></span>
                </label>
                <div class="control">
                    <input name="cvv"
                           id="cvv"
                           title="<?= __('CVV') ?>"
                           class="input-text"
                           data-validate="{'required-number':true}"
                           type="password"
                    />
                </div>
            </div>

            <!-- Card Holder Name - cc_name -->
            <div class="field cardname required">
                <label class="label" for="cardname">
                    <span><?= __('Name on Card') ?></span>
                </label>
                <div class="control">
                    <input name="cardname"
                           id="cardname"
                           title="<?= __('Name on Card') ?>"
                           class="input-text"
                           type="text"
                           data-validate="{'required':true}"
                    />
                </div>
            </div>

            <!-- Street Address - cc_addr_street_one -->
            <div class="field bilstre1 required">
                <label class="label" for="bilstre1">
                    <span><?= __('Street Line 1') ?></span>
                </label>
                <div class="control">
                    <input name="bilstre1"
                           id="bilstre1"
                           title="<?= __('Street Line 1') ?>"
                           class="input-text"
                           type="text"
                           data-validate="{'required':true}"
                    />
                </div>
            </div>

            <!-- Street Address - cc_addr_street_two -->
            <div class="field bilstre2">
                <label class="label" for="bilstre2">
                    <span><?= __('Street Line 2') ?></span>
                </label>
                <div class="control">
                    <input name="bilstre2"
                           id="bilstre2"
                           title="<?= __('Street Line 2') ?>"
                           class="input-text"
                           type="text"
                    />
                </div>
            </div>

            <!-- City - cc_addr_city -->
            <div class="field bilcity required">
                <label class="label" for="bilcity">
                    <span><?= __('City') ?></span>
                </label>
                <div class="control">
                    <input name="bilcity"
                           id="bilcity"
                           title="<?= __('City') ?>"
                           class="input-text"
                           type="text"
                           data-validate="{'required':true}"
                    />
                </div>
            </div>

            <div class="field bilprov required">
                <label class="label" for="bilprov">
                    <span><?= __('Province / State') ?></span>
                </label>
                <div class="control">
                    <input name="region"
                           id="region"
                           type="text"
                           data-validate="{'validate-required-state':true}"
                    />
                    <select name="state"
                            id="state"
                            data-validate="{'validate-required-state':true}"
                    >
                    </select>
                </div>
            </div>

            <!-- Zip/Postal Code - cc_addr_postcode -->
            <div class="field bilpstl required">
                <label class="label" for="bilpstl">
                    <span><?= __('Postal Code') ?></span>
                </label>
                <div class="control">
                    <input name="bilpstl"
                           id="bilpstl"
                           title="<?= __('Postal Code') ?>"
                           class="input-text"
                           type="text"
                           data-validate="{'required':true}"
                    />
                </div>
            </div>

            <!-- Country - cc_addr_country_id -->
            <div class="field bilctry required">
                <label class="label" for="bilctry">
                    <span><?= __('Country') ?></span>
                </label>
                <div class="control">
                    <select name="bilctry"
                            id="bilctry"
                            title="<?= __('Country') ?>"
                            data-validate="{'required':true}"
                    >
                        <option value=""></option>
                        <?php foreach ($block->getAllowedCountries() as $country): ?>
                            <option value="<?= /* @noEscape */ $country['value'] ? $escaper->escapeHtml($country['value']) : '' ?>">
                                <?= $escaper->escapeHtml($country['type']) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        </fieldset>

        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" title="<?= __('Submit') ?>" class="action submit">
                    <span><?= __('Submit') ?></span>
                </button>
            </div>
        </div>
    </form>
</div>

<script>
    require([
        'jquery',
        'mage/validation',
        'Magento_Payment/js/model/credit-card-validation/validator',
        'ECInternet_Paytelligence/js/region-updater'
    ], function ($, validation, validator, regionUpdater) {
        'use strict';

        new regionUpdater({
            'regionInputId': '#region',
            'regionListId': '#state',
            'postcodeId': '#bilpstl',
            'regionJson': JSON.parse('<?= $escaper->escapeJs($block->getRegionJson()) ?>')
        }, '#bilctry')

        $.validator.addMethod('validate-required-state',
            function (value) {
                return value.length > 0;
            },
            $.mage.__('Please enter a valid state.')
        );
    });
</script>
